### ISSUE TITLE
Holding register and bits

### ISSUE THREAD

**Issue by tomasinouk** [Argonne-National-Laboratory/node-red-contrib-modbustcp#13]
Hi, is there a way to read specific bits in holding register?
Thank you

**Comment by marcusjelsch** [comment]
Yes. U can try to read it like a coil.

Am 16.07.2017 10:28 schrieb "Tomas Blaha" <notifications@github.com>:

**Comment by tomasinouk** [comment]
hi, thanks for quick response,
I tried that and no luck there.

for example the holding register address is 256
e.g. 40256
I tried to read the coil 256 with quantity of 15 (assuming reading bits from 0-14)

I got nothing back though, any suggestion?
Thank you

**Comment by marcusjelsch** [comment]
Does ur modbus device support coils?

2017-07-16 12:02 GMT+02:00 Tomas Blaha <notifications@github.com>:

**Comment by tomasinouk** [comment]
it doesn't only holding registers

**Comment by marcusjelsch** [comment]
Search my threads. I have had the same problems. There u will find the
solution.

Am 16.07.2017 14:23 schrieb "Tomas Blaha" <notifications@github.com>:

it doesn't only holding registers

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Argonne-National-Laboratory/node-red-contrib-modbustcp/issues/13#issuecomment-315605892>,
or mute the thread

**Comment by tomasinouk** [comment]
will do and post here, if I find a solution

**Comment by jayharper** [comment]
Why don't you just read the entire holding register and use a function block with a bit mask to read the specific bit you are interested in?

**Comment by marcusjelsch** [comment]
Do u have an example?

Am 17.07.2017 17:19 schrieb "Jason D. Harper" <notifications@github.com>:

**Comment by tomasinouk** [comment]
Hi, sorry for long delay on my side.

@jayharper thank you for suggestion. That led me to using function node with this code

```javascript
var a = msg.payload[0];
var b = [];
for (var i = 0; i < 16; i++)
  b[i] = (a >> i) & 1;

var a = msg.payload[1];
var c = [];
for (var i = 0; i < 16; i++)
  c[i] = (a >> i) & 1;

b = b.concat(c);
msg.payload = b
return msg;
```
I am reading two registers, let say 500 and 501, that is the array in `msg.payload[]` and each register has 16bits, which I am accessing in `for loop`.

I do have sneaky suspicion, that I am not applying your suggestion correctly though. 

I can post whole flow, if needed.

**Comment by jayharper** [comment]
Try this.  Feel free to edit as necessary.
`msg.payload = [];
msg.payload[0] = 0xAACC;
msg.payload[1] = 0X00FF;

function isNthBitSet (c, n) {
    var mask = [1,2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768];
    return ((c & mask[n]) !== 0);
}

var b = [];
for (var i = 0; i < 16; i++)
{
  b[i] = (isNthBitSet(msg.payload[0], i));
}

var c = [];
for (var i = 0; i < 16; i++)
  c[i] = (isNthBitSet(msg.payload[1], i));

b = b.concat(c);
msg.payload = b;
return msg;`
