### ISSUE TITLE
working on raspberry pi

### ISSUE THREAD

**Issue by burak8758** [Argonne-National-Laboratory/node-red-contrib-modbustcp#14]
Hello,

İs it possible working on raspberry pi with modbustcp package. I have succesfully install modbustcp node to my raspberry pi. But I couldn't connect with my s7-1200 on modbus tcp. Could you help me please?

**Comment by jayharper** [comment]
If the node successfully installed then this seems like a firewall or setup issue.

**Comment by burak8758** [comment]
How can i change my firewall setting for my raspberry? Also is there any special settings for s7-1200.
