### ISSUE TITLE
dataType capitalization bug

### ISSUE THREAD

**Issue by scottrcarlson** [Argonne-National-Laboratory/node-red-contrib-modbustcp#19]
I found in modbustcp.js

      // Check to see if the incoming message overrides the dataTpye
      if (msg.hasOwnProperty("dataType") ) {
        dataType = msg.datatype;
      } else {
        dataType = node.dataType;
      }

should be
      if (msg.hasOwnProperty("dataType") ) {
        dataType = msg.dataType;
      } else {
        dataType = node.dataType;
      }

the msg.dataType. I took me a bit to realize what was going on. I had to actually send both datatype and dataType to trip the logic then read the value.

Thanks for the library!

**Comment by bnystrom** [comment]
Thanks for the report. Fixed in v1.2.3
