### ISSUE TITLE
Waiting for missing types to be registered - node-red 0.19.4

### ISSUE THREAD

**Issue by tb4450** [Argonne-National-Laboratory/node-red-contrib-modbustcp#25]
thanks for offering this software. i appreciate it very much.

i used verson 1.2.1 up to now. it worked well. no issues.

then i updated node-red to version 0.19.4 and with that i updated to version 1.2.3 of modbustcp. but that did not work. i could install it but node-red didn't find it. giving this message in the log.

0|node-red | 26 Oct 20:04:44 - [info] Waiting for missing types to be registered:
0|node-red | 26 Oct 20:04:44 - [info]  - modbustcp-server
0|node-red | 26 Oct 20:04:44 - [info]  - modbustcp-read
0|node-red | 26 Oct 20:04:44 - [info]  - modbustcp-write

node -v is v6.10.0
npm -v is 6.4.1

now i downgraded to version 1.2.1 and it's working again.

any idea? thanks and cheers.

**Comment by bnystrom** [comment]
I'm not sure why you weren't given an error when installing, but the package.json states that we require a minimum of node 7.5.0 for this release. I would recommend upgrading your node.js to at a minimum 8.x if not the latest 10.x.

So, in short, I'm guessing that the newer releases of some of the node modules we rely on for this release require a newer release of node than you are using.

If you upgrade node, please let me know if it works for you or not.

**Comment by tb4450** [comment]
Thanks, bnystrom. At the moment i need to wait before upgrading node itself (because of other dependencies). But it's good to know what the reason was.
