### ISSUE TITLE
Read AND Write Connection to one Modbus-Server

### ISSUE THREAD

**Issue by Markus-** [Argonne-National-Laboratory/node-red-contrib-modbustcp#27]
I have an AC which is controllable by ModBus.

So I tried the Read-Node and can query the AC without any problems.
When I implement a Write-Node it can not connect to the Server as long as the Read-Node works.

How could I achieve reading in intervals and writing as needed to the same server?
Is this possible?

Regards
Markus

**Comment by bnystrom** [comment]
As long as you are using a single (the same) server connection, this should work. We've seen modbus servers that only allow a single connection. Curious if you created two separate server connections or if you put the read and the write nodes on separate tabs?

**Comment by Markus-** [comment]
I realized it with Flex Getter / Flex Write - this way it's working.
