### ISSUE TITLE
Auto Reconnect

### ISSUE THREAD

**Issue by thegunshow** [Argonne-National-Laboratory/node-red-contrib-modbustcp#5]
Hi

I am reading data using the Modbus "master" node. if it losses the connection will it automatically try and reconnect, do you know what the reconnect time is?

Thanks
Great node to have!!

**Comment by thehellodonkey** [comment]
Agreed that this is a great node to have. Unfortunately, for me at least, if the connection is lost it will never reconnect without restarting/redeploying the node manually. It would be extremely helpful in my use case (and probably most others) if there were auto-reconnect functionality.
Thanks!

**Comment by jayharper** [comment]
Added auto-reconnect functionality with recent update.  You can also set the Reconnect Interval (s) on the connection config tab.
