### ISSUE TITLE
Node settings in the flow ?

### ISSUE THREAD

**Issue by Franck911** [Argonne-National-Laboratory/node-red-contrib-modbustcp#7]
Hello !
Do you plan to add the ability to configure settings (Type (function code), address, modbustcp-server settings...) directly in the flow instead of just in the node ?
This would be so convenient, especially when data are variable.
Thanks

**Comment by jayharper** [comment]
Yes. Version 1.1.x has this capability.

**Comment by WeeSee** [comment]
Is there any documentation about this? Can the modbustcp-server be specified in the payload? 

That would be great!

**Comment by ShyamBhattacharyya** [comment]
Same question is here. How to change modbusTCP ipAddress and port using payload. What will be the correct syntax for that?
