### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by nilesh441** [Argonne-National-Laboratory/node-red-contrib-modbustcp#8]
Why this node fails with serialport error? This is modbus tcp, I don't want to install serial port. My board does not support serial port. I am getting make error on serial port while installing this node. Why can't I use only modbustcp?

**Comment by burak8758** [comment]
I have same problem,too. I couldn't find solution yet.

**Comment by jayharper** [comment]
This project utilizes the jsmodbus project.  This is a jsmodbus issue.
