### ISSUE TITLE
Error when using the status (all) node with the modbustcp node

### ISSUE THREAD

**Issue by Joesove** [Argonne-National-Laboratory/node-red-contrib-modbustcp#9]
The error is "TypeError: Cannot read property 'hasOwnProperty' of null”

In the modbustcp.js status is cleared with `node.status(null)` it should be `node.status({})`

See here: http://nodered.org/docs/writing-functions.html#adding-status

**Comment by jayharper** [comment]
fixed in version 1.x.x
